[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_upload.flash_size = 4MB
board_build.partitions = default.csv
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-std=gnu++17

monitor_speed = 115200

board_build.arduino.usb_mode = otg
board_build.arduino.usb_cdc = on
board_build.arduino.usb_msc = on
board_build.arduino.usb_dfu = off